### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by renovoto** [andresamayadiaz/FrontAccountingSimpleAPI#24]
Hi i did all the recommended settings but it is not working 
url: http://accounting.loc/modules/api/category(this is virtual host on my local machine)

i also did the util.php settings Please Help

**Comment by renovoto** [comment]
i am sorry i did not understand the composer slim install. i had not installed slim that was the problem sorry!

**Comment by andresamayadiaz** [comment]
Ok, hope it is working fine now.
