### ISSUE TITLE
Integration with OSPOS

### ISSUE THREAD

**Issue by SteveIreland** [andresamayadiaz/FrontAccountingSimpleAPI#27]
The last commit here was back in September 2015.  

I need to decide if I can/should use this for integration between OSPOS and FrontAccounting.

I need to add more interfaces and possibly beef up the security a bit.  If I do that will you want those as contributions to this project?

**Comment by andresamayadiaz** [comment]
Hi Steve. I am happy to hear you are interested. 

Sure you can use this as a base interface, as you say it will need adjustments and sure please send the merge request whenever you can.

Enviado desde mi iPhone
