### ISSUE TITLE
APIs not working, just follow the steps you documented

### ISSUE THREAD

**Issue by marwan2** [andresamayadiaz/FrontAccountingSimpleAPI#52]
I can't use the APIs, I have downloaded and extracted the zip file into http://localhost/frontaccounting/modules/api/

And after calling for example:
http://localhost/frontaccounting/modules/api/bankaccounts

The output is 

`<center><center><table width='20%' cellpadding='2' cellspacing='0'>
<tr>
<td align=center><a href='javascript:goBack();'>Back</a></td>
</tr>
</table></center>
</center><br></div></td></tr></table>
<table class='bottomBar2'>
<tr><td class='bottomBarCell'>11/13/2018 | 12:44 pm</td>
<td id='hotkeyshelp'></td></tr></table>
</td></tr> </table>
<table align='center' id='footer'>
<tr>
<td align='center' class='footer'><a target='_blank' href='http://frontaccounting.com' tabindex='-1'><font color='#ffffff'>FrontAccounting 2.4.4 - Theme: default - </font></a></td>
</tr>
<tr>
<td align='center' class='footer'><a target='_blank' href='http://frontaccounting.com' tabindex='-1'><font color='#ffff00'>FrontAccounting</font></a></td>
</tr>
</table><br><br>
<script type='text/javascript'>
		_focus = '';
		_validate = [  ];
		var editors = [  ];
	</script>
<script type="text/javascript"></script>
</body></html>
`

**Comment by andresamayadiaz** [comment]
You might need to enable mod_rewrite in apache and also in the directory config AllowOverride to All

**Comment by cambell-prince** [comment]
More a "note to self". If this has fixed the issue let us know and we'll update the documentation in README's Installation section to make the required installation more clear.
