### ISSUE TITLE
How to perform add journal entry - curl post request

### ISSUE THREAD

**Issue by LevisKimathi** [andresamayadiaz/FrontAccountingSimpleAPI#53]
Hi,
Have been struggling to do curl post to the journal api. I am getting a _{"code":412,"success":0,"msg":"items must exist and be an array"}_. Would appreciate some help. Below is what I have tried. On doing a raw body **postman** request it enters successfully. But for this I can't figure out the issue.
```
<?php
    			
$data = array(
	'currency' => 'KS',
	'document_ref' => 'INV54321',
	'reference' => '1',
	'memo' => 'curl test',
	'items' => array(
	array('account_code'=>'1000','amount'=>'-200','memo'=>'curl test'),
	array('account_code'=>'2000','amount'=>'200','memo'=>'curl test'),
	)
);
$json_data = http_build_query($data);

$headers = array(
	'Content-Type: text/plain',
);

$curl = curl_init();

curl_setopt_array($curl, array(
CURLOPT_URL => "http://localhost/fa/modules/api/journal/",
CURLOPT_RETURNTRANSFER => true,
CURLOPT_CUSTOMREQUEST => "POST",
CURLOPT_POSTFIELDS => $json_data,
CURLOPT_HTTPHEADER => $headers,
));

$response = curl_exec($curl);

curl_close($curl);

echo $response;

```

**Comment by andresamayadiaz** [comment]
Try to use json_encode for your data variable. 

__________________________
Fco. Andrés Amaya Díaz

**Comment by LevisKimathi** [comment]
I tried that it didn't work. Still saying it needs an array

**Comment by LevisKimathi** [comment]
> Try to use json_encode for your data variable.
> […](#)
> __________________________ Fco. Andrés Amaya Díaz
> El 20 dic 2020, a la(s) 19:26, Levis Kimathi ***@***.***> escribió: ﻿ Hi, Have been struggling to do curl post to the journal api. I am getting a {"code":412,"success":0,"msg":"items must exist and be an array"}. Would appreciate some help. Below is what I have tried. On doing a raw body post man request it enters successfully. But for this I can't figure out the issue. `<?php $data = array( 'currency' => 'KS', 'document_ref' => 'INV54321', 'reference' => '1', 'memo' => 'curl test', 'items' => array( array('account_code'=>'1000','amount'=>'-200','memo'=>'curl test'), array('account_code'=>'2000','amount'=>'200','memo'=>'curl test'), ) ); $json_data = http_build_query($data); $headers = array( 'Content-Type: text/plain', ); $curl = curl_init(); curl_setopt_array($curl, array( CURLOPT_URL => "http://localhost/powergaserp/modules/api/journal/", CURLOPT_RETURNTRANSFER => true, CURLOPT_CUSTOMREQUEST => "POST", CURLOPT_POSTFIELDS => $json_data, CURLOPT_HTTPHEADER => $headers, )); $response = curl_exec($curl); curl_close($curl); echo $response;` — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I tried that it didn't work. Still saying it needs an array
